# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jane Du
email: jane.z.du@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The musings and messing-arounds of a distracted student.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhuangjindu.github.io" # the base hostname & protocol for your site
twitter_username: janezdu
github_username:  zhuangjindu

# Build settings
markdown: kramdown
